from enum import Enum


class EvidenceType(str, Enum):
    # Standard proposed categories
    HEADER = "header"
    COOKIE = "cookie"
    HTML = "html"
    SCRIPT = "script"
    TLS = "tls"
    DNS = "dns"
    PORT = "port"
    BANNER = "banner"
    ASSET = "asset"
    META = "meta"
    SERVER = "server"
    AUTHENTICATION = "authentication"

    # Additional categories generated by tools
    HTTP_CODE = "http_code"
    SERVICE = "service"
    TLS_EXPIRY = "tls_expiry"
