from enum import Enum


class EvidenceType(str, Enum):
    # Standard proposed categories
    HEADER = "header"
    COOKIE = "cookie"
    HTML = "html"
    SCRIPT = "script"
    TLS = "tls"
    DNS = "dns"
    PORT = "port"
    BANNER = "banner"
    ASSET = "asset"
    META = "meta"
    SERVER = "server"
    AUTHENTICATION = "authentication"

    # Additional categories generated by tools
    HTTP_CODE = "http_code"
    SERVICE = "service"
    TLS_EXPIRY = "tls_expiry"


class TechnologyCategory(str, Enum):
    SERVER = "Web Server"
    CMS = "CMS"
    CDN = "CDN / Cloud Provider"
    CLOUD = "Cloud Provider"
    SERVICE = "Service"
    FRAMEWORK = "Frontend Framework"
    LIBRARY = "JavaScript Library"
    LANGUAGE = "Programming Language"
    BACKEND = "Backend Framework"
    AUTH = "Authentication Provider"
    CSS = "CSS Framework"
